name: Keep Render Alive
on:
  schedule:
    # Se ejecuta cada 14 minutos para evitar que Render se duerma
    - cron: '*/14 * * * *'
  
  workflow_dispatch:

jobs:
  ping-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Endpoint
        run: curl -f https://indexed-search.onrender.com/status